#!/bin/bash

#
# OPAM 
# ----

sudo yum install make 
sudo yum install m4 
sudo yum install gcc
sudo yum install git
sudo yum install unzip

wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin

sudo yum install ncurses
sudo yum install ncurses-devel

#
# Protobuf Development installation
# ---------------------------------

PB_VERSION=3.1.0
wget https://github.com/google/protobuf/releases/download/v3.1.0/protobuf-cpp-$PB_VERSION.tar.gz
tar xzvf protobuf-cpp-$PB_VERSION.tar.gz 

sudo yum install autoconf
sudo yum install automake
sudo yum install libtool
sudo yum install g++ 
sudo yum install gcc-c++ 

cd protobuf-$PB_VERSION
./configure
make
make check
sudo make install
sudo ldconfig

#
# Rocks DB development installation
# --------------
export ROCKS_VERSION=4.13.5
wget https://github.com/facebook/rocksdb/archive/v$ROCKS_VERSION.tar.gz
tar xzvf v$ROCKS_VERSION.tar.gz 
cd rocksdb-$ROCKS_VERSION/
sudo apt-get install libgflags-dev 
sudo apt-get install libsnappy-dev 
sudo apt-get install zlib1g-dev 
sudo apt-get install libbz2-dev 
sudo apt-get install libzstd-dev 
make static_lib 
#make share_lib 
sudo make install


#
# Tools 
# -----

sudo  yum install tree

#
#
# SSH keys for github ...
# -----------------------

# check if ~/.ssh/id_rsa is not present already 
# if not then generated using the 2 command below

ssh-keygen -t rsa -b 4096 -C "maxime.ransan@gmail.com" 
ssh-add ~/.ssh/id_rsa 

# Copy content of public key: ~/.ssh/id_rsa.pub to 
# the gitbub account
# https://github.com/settings/keys

#
# 
# Setup Docker

sudo usermod -aG docker ec2-user
