#!/bin/bash

#
# OPAM 
# ----

sudo yum install make 
sudo yum install m4 
sudo yum install gcc
sudo yum install git
sudo yum install unzip

wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin

sudo yum install ncurses
sudo yum install ncurses-devel

#
# Protobuf Development installation
# ---------------------------------

PB_VERSION=3.1.0
wget https://github.com/google/protobuf/releases/download/v3.1.0/protobuf-cpp-$PB_VERSION.tar.gz
tar xzvf protobuf-cpp-$PB_VERSION.tar.gz 

sudo yum install autoconf
sudo yum install automake
sudo yum install libtool
sudo yum install g++ 
sudo yum install gcc-c++ 

cd protobuf-$PB_VERSION
./configure
make
make check
sudo make install
sudo ldconfig

#
# Tools 
# -----

sudo  yum install tree

#
#
# SSH keys for github ...
# -----------------------

ssh-keygen -t rsa -b 4096 -C "maxime.ransan@gmail.com" 
ssh-add ~/.ssh/id_rsa 

#
# 
# Setup Docker

sudo usermod -aG docker ec2-user
