#!/bin/bash

#
# OPAM 
# ----

sudo yum install m4 
sudo yum install gcc
sudo yum install git

wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin

sudo yum install ncurses
sudo yum install ncurses-devel

#
# Protobuf Development installation
# ---------------------------------

wget https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/protobuf-cpp-3.0.0-beta-2.tar.gz 
tar xzvf protobuf-cpp-3.0.0-beta-2.tar.gz 

sudo yum install autoconf
sudo yum install automake
sudo yum install libtool
sudo yum install g++ 
sudo yum install unzip
sudo yum install gcc-c++ 

cd protobuf-3.0.0-beta-2/
./configure
make
make check
sudo make install
sudo ldconfig

#
# Tools 
# -----

sudo yum install tree
